/**
 * Emits the baseline-seed migration from the shared builder.
 * Run:  npx vite-node scripts/genAccessProfileSeeds.ts
 */
import { writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { buildSeeds, type Seed } from "../src/supabase/seeds/accessProfileSeedBuilder";

function sqlString(v: string | null): string {
  return v === null ? "NULL" : `'${v.replace(/'/g, "''")}'`;
}

function emit(seeds: Seed[]): string {
  const lines: string[] = [
    "-- ============================================================================",
    "-- 130: Access Profile baseline seeds (GENERATED — do not hand-edit)",
    "-- ============================================================================",
    "-- Generated by scripts/genAccessProfileSeeds.ts from the patterns in",
    "-- src/supabase/seeds/accessProfileSeedBuilder.ts (policy: ACCESS_PROFILE_SEEDS.md).",
    "-- Self-contained + idempotent: clears existing baselines, re-inserts all.",
    "-- Prerequisites: 128 (target_service), 129 (is_baseline).",
    "-- ============================================================================",
    "",
    "DELETE FROM public.access_profiles WHERE is_baseline = true;",
    "",
    "INSERT INTO public.access_profiles",
    "  (name, description, target_department, target_role, target_service,",
    "   module_grants, visibility_scope, visibility_departments, is_baseline, is_active)",
    "VALUES",
  ];
  const rows = seeds.map((s) =>
    `  (${sqlString(s.name)}, 'Auto-generated baseline seed.', ` +
    `${sqlString(s.department)}, ${sqlString(s.role)}, ${sqlString(s.service)}, ` +
    `${sqlString(JSON.stringify(s.grants))}::jsonb, ${sqlString(s.visibility)}, NULL, true, true)`,
  );
  lines.push(rows.join(",\n") + ";", "");
  return lines.join("\n");
}

const seeds = buildSeeds();
const __dirname = dirname(fileURLToPath(import.meta.url));
const outPath = resolve(__dirname, "../src/supabase/migrations/130_access_profile_seeds.sql");
writeFileSync(outPath, emit(seeds), "utf8");
console.log(`Generated ${seeds.length} baseline seeds → ${outPath}`);
