/**
 * Emits migration 198 — DB-level grant-cascade materialization.
 * Run:  npx vite-node scripts/genGrantCascadeMigration.ts
 *
 * WHY: the parent→child-tab cascade is materialized in exactly one writer today
 * (the admin save path, accessGrantUtils.resolveCascadedGrants). Every other
 * writer (seed migrations, prod→dev clone, create-user edge fn) stores raw
 * parent grants, so the runtime resolver (exact-key, no cascade) denies the
 * un-materialized child tabs → blank tabs (NEU-030). This migration moves the
 * cascade into the DB as a write-time trigger + backfills existing rows, so the
 * admin grid (display cascade), storage, and the resolver can never disagree.
 *
 * The parent→child EDGES are generated here from ACCESS_SCHEMA (single source of
 * truth) so they can never drift from the TS engine: child set = own tabs +
 * containsModuleIds, filtered by the SAME isActionApplicable() the editor uses.
 */
import { writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { ALL_MODULE_NODES } from "../src/config/access/accessSchema";
import { isActionApplicable } from "../src/config/access/actionApplicability";
import type { ActionId } from "../src/components/admin/permissionsConfig";

const ACTIONS: ActionId[] = ["view", "create", "edit", "approve", "delete", "export", "amend"];

function buildEdges(): Array<[string, string]> {
  const seen = new Set<string>();
  const edges: Array<[string, string]> = [];
  for (const node of ALL_MODULE_NODES) {
    const children = [
      ...node.tabs.map((t) => t.moduleId),
      ...((node.containsModuleIds ?? []) as string[]),
    ];
    for (const child of children) {
      if (child === node.moduleId) continue;
      for (const action of ACTIONS) {
        if (!isActionApplicable(child, action)) continue;
        const parentKey = `${node.moduleId}:${action}`;
        const childKey = `${child}:${action}`;
        const dedup = `${parentKey}|${childKey}`;
        if (seen.has(dedup)) continue;
        seen.add(dedup);
        edges.push([parentKey, childKey]);
      }
    }
  }
  edges.sort((a, b) => a[0].localeCompare(b[0]) || a[1].localeCompare(b[1]));
  return edges;
}

function emit(edges: Array<[string, string]>): string {
  const values = edges
    .map(([p, c]) => `  ('${p.replace(/'/g, "''")}', '${c.replace(/'/g, "''")}')`)
    .join(",\n");

  return `-- ============================================================================
-- 198: Grant-cascade materialization at the DB write layer (NEU-030)
-- ============================================================================
-- GENERATED by scripts/genGrantCascadeMigration.ts from ACCESS_SCHEMA — do not
-- hand-edit the edge list; re-run the generator after any schema change.
--
-- Problem: parent module grants (e.g. pricing_projects:view) were stored without
-- their child tab grants (pricing_projects_info_tab:view, ...). The resolver does
-- exact-key lookup with no cascade, so child tabs rendered blank even though the
-- admin grid showed them granted (display-only cascade). Only the admin save path
-- materialized the cascade; seeds / clone / edge fn did not.
--
-- Fix: (1) a generated parent→child edge table, (2) a pure function that expands
-- a module_grants blob, (3) BEFORE INSERT/UPDATE triggers on both grant tables so
-- EVERY writer materializes, (4) a one-time backfill of existing rows.
-- Explicit child grants (incl. explicit false denials) always win over cascade.
-- ============================================================================

-- 1. Edge table (parent_key -> child_key), generated from the schema -----------
create table if not exists public.access_cascade_edges (
  parent_key text not null,
  child_key  text not null,
  primary key (parent_key, child_key)
);

comment on table public.access_cascade_edges is
  'GENERATED from ACCESS_SCHEMA by scripts/genGrantCascadeMigration.ts. Each row: granting parent_key cascades the same boolean to child_key unless child is explicit. Re-generate on schema change.';

truncate public.access_cascade_edges;
insert into public.access_cascade_edges (parent_key, child_key) values
${values};

-- 2. Pure materializer: parent grants fill in absent child grants --------------
create or replace function public.materialize_grant_cascade(grants jsonb)
returns jsonb
language sql
immutable
as $function$
  -- explicit keys already in the grants blob win (we only add ABSENT children),
  -- so a hand-set child (true OR false) is never overwritten by the cascade.
  select coalesce(grants, '{}'::jsonb) || coalesce(
    (
      select jsonb_object_agg(e.child_key, grants -> e.parent_key)
      from public.access_cascade_edges e
      where grants ? e.parent_key
        and not (grants ? e.child_key)
    ),
    '{}'::jsonb
  );
$function$;

-- 3. Write-time triggers on both grant tables ----------------------------------
create or replace function public.trg_materialize_grant_cascade()
returns trigger
language plpgsql
as $function$
begin
  new.module_grants := public.materialize_grant_cascade(new.module_grants);
  return new;
end;
$function$;

drop trigger if exists materialize_cascade_on_overrides on public.permission_overrides;
create trigger materialize_cascade_on_overrides
  before insert or update of module_grants on public.permission_overrides
  for each row execute function public.trg_materialize_grant_cascade();

drop trigger if exists materialize_cascade_on_profiles on public.access_profiles;
create trigger materialize_cascade_on_profiles
  before insert or update of module_grants on public.access_profiles
  for each row execute function public.trg_materialize_grant_cascade();

-- 4. One-time backfill (heal existing rows) ------------------------------------
update public.permission_overrides
   set module_grants = public.materialize_grant_cascade(module_grants)
 where module_grants is not null;

update public.access_profiles
   set module_grants = public.materialize_grant_cascade(module_grants)
 where module_grants is not null;
`;
}

const edges = buildEdges();
const __dirname = dirname(fileURLToPath(import.meta.url));
const outPath = resolve(
  __dirname,
  "../src/supabase/migrations/198_grant_cascade_materialization.sql",
);
writeFileSync(outPath, emit(edges), "utf8");
console.log(`Generated ${edges.length} cascade edges → ${outPath}`);
